name: Run tox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
        platform: [x32, x64]
        exclude:
          - os: macos-latest  # macos-10.15
            platform: x32
          - os: ubuntu-latest
            platform: x32
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install --progress-bar=off  -rci/requirements.txt
    - name: Test
      run: tox -v
      env:
        PLATFORM: ${{ matrix.platform }}
